# Generated by Django 2.0 on 2018-08-09 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_text', models.CharField(max_length=250, unique=True)),
                ('created_Date', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 13, 56, 14, 676410))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
