# Generated by Django 2.0 on 2018-08-24 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 8, 24, 10, 49, 29, 742346))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
