# Generated by Django 2.0 on 2018-08-24 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed', '-timestamp']},
        ),
        migrations.AddField(
            model_name='todo',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 11, 39, 3, 221237)),
        ),
    ]
